"use client";

import React, { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Sparkles, X, Loader2, Send } from "lucide-react";
import { trpc } from "@/src/trpc/client";
import { toast } from "sonner";
import { useRouter } from "next/navigation";

interface AiAssistantProps {
  isOpen: boolean;
  onClose: () => void;
}

export function AiAssistant({ isOpen, onClose }: AiAssistantProps) {
  const [prompt, setPrompt] = useState("");
  const router = useRouter();

  const { mutate: createForm, isPending } = trpc.forms.create.useMutation({
    onSuccess: (data) => {
      toast.success("AI generated form successfully!");
      onClose();
      if (data?.id) {
        router.push(`/forms/${data.id}/builder`);
      }
    },
    onError: (err) => {
      toast.error(err.message || "Failed to generate form");
    }
  });

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!prompt.trim()) return;
    
    // For now, just use the prompt as the form name
    createForm({
      name: prompt.trim(),
      description: "Generated by AI Assistant"
    });
  };

  return (
    <AnimatePresence>
      {isOpen && (
        <>
          {/* Backdrop */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={onClose}
            className="fixed inset-0 z-50 bg-black/20 backdrop-blur-sm"
          />

          {/* Slide-up Panel */}
          <motion.div
            initial={{ opacity: 0, y: 100, scale: 0.95 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: 100, scale: 0.95 }}
            transition={{ type: "spring", stiffness: 300, damping: 30 }}
            className="fixed bottom-6 right-6 z-50 w-[380px] bg-white/80 backdrop-blur-xl border border-neutral-200/80 shadow-2xl rounded-3xl overflow-hidden flex flex-col"
          >
            {/* Header */}
            <div className="bg-gradient-to-r from-violet-600 to-fuchsia-600 p-6 relative overflow-hidden">
              <div className="absolute top-[-50%] right-[-10%] w-[200px] h-[200px] bg-white/20 blur-[50px] rounded-full pointer-events-none" />
              <button 
                onClick={onClose}
                className="absolute top-4 right-4 text-white/70 hover:text-white transition-colors"
              >
                <X size={20} />
              </button>
              <div className="flex items-center gap-3 relative z-10">
                <div className="w-10 h-10 bg-white/20 rounded-xl flex items-center justify-center backdrop-blur-md border border-white/30">
                  <Sparkles className="text-white" size={20} />
                </div>
                <div>
                  <h3 className="text-white font-bold text-lg">AI Form Assistant</h3>
                  <p className="text-white/80 text-xs font-medium">Describe what you need built.</p>
                </div>
              </div>
            </div>

            {/* Content Area */}
            <div className="p-6 bg-white flex flex-col gap-4">
              <p className="text-xs text-neutral-500 font-medium">
                I can help you instantly generate a complete form with appropriate fields, validations, and a matching theme.
              </p>
              
              <form onSubmit={handleSubmit} className="flex flex-col gap-3">
                <div className="relative">
                  <textarea
                    value={prompt}
                    onChange={(e) => setPrompt(e.target.value)}
                    disabled
                    placeholder="e.g. A feedback form for my new SaaS product with a 1-5 rating scale..."
                    className="w-full h-28 bg-neutral-50 border border-neutral-200 rounded-2xl p-4 text-sm resize-none focus:outline-none focus:ring-2 focus:ring-violet-500/20 disabled:bg-neutral-100 disabled:cursor-not-allowed"
                  />
                  <div className="absolute inset-0 flex items-center justify-center bg-white/60 backdrop-blur-[1px] rounded-2xl">
                    <span className="bg-neutral-900 text-white text-[10px] font-bold uppercase tracking-widest px-3 py-1.5 rounded-full shadow-lg">
                      AI generation coming soon
                    </span>
                  </div>
                </div>

                <button
                  type="submit"
                  disabled={true}
                  className="flex items-center justify-center gap-2 w-full bg-neutral-900 hover:bg-neutral-800 text-white font-semibold py-3 rounded-xl shadow-md transition-all disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  {isPending ? (
                    <Loader2 size={18} className="animate-spin" />
                  ) : (
                    <>
                      <Send size={16} /> Generate Form
                    </>
                  )}
                </button>
              </form>
            </div>
          </motion.div>
        </>
      )}
    </AnimatePresence>
  );
}
